export const GYM_INFO = {
  name: 'Train 2 Infinity',
  tagline: 'Push Beyond Limits',
  rating: 4.9,
  reviewCount: 247,
  phone: '+91 85969 99000',
  email: 'test000555786@gmail.com',
  address: {
    street: 'Near Salipur High School Field, Salipur',
    area: 'Chandradeipur, Salipur',
    city: 'Salipur',
    state: 'Odisha',
    pincode: '754202',
    full: "Near Salipur High School Field, Chandradeipur, Salipur, Odisha - 754202, train 2 infinity ",
  },
  hours: {
    weekdays: '5:00 AM – 10:00 PM',
    saturday: '5:00 AM – 10:00 PM',
    sunday: 'Closed',
    label: 'Mon–Sat: 5AM–10PM | Sun: Closed',
  },
  social: {
    instagram: 'https://instagram.com', 
    facebook: 'https://facebook.com',
    youtube: 'https://youtube.com',
    twitter: 'https://twitter.com',
  },
  stats: [
    { value: '500+', label: 'Active Members' },
    { value: '4.9★', label: 'Google Rating' },
    { value: '10+', label: 'Expert Trainers' },
    { value: '6+', label: 'Programs' },
  ],
  features: [
    {
      icon: '🏋️',
      title: 'Premium Equipment',
      description: 'State-of-the-art strength and cardio machines from top global brands.',
    },
    {
      icon: '👨‍🏫',
      title: 'Expert Trainers',
      description: 'Nationally certified coaches with proven track records of client transformation.',
    },
    {
      icon: '📊',
      title: 'Science-Based Plans',
      description: 'Evidence-based programming customized to your goals and body composition.',
    },
    {
      icon: '🥗',
      title: 'Nutrition Coaching',
      description: 'Comprehensive diet planning and nutritional guidance for maximum results.',
    },
    {
      icon: '📱',
      title: 'Progress Tracking',
      description: 'Monthly assessments, body composition analysis, and digital progress reports.',
    },
    {
      icon: '🏆',
      title: 'Proven Results',
      description: '500+ success stories. Average member sees visible results within 30 days.',
    },
  ],
};

export const MEMBERSHIP_PLANS = [
  {
    id: 'monthly',
    name: 'Monthly',
    price: 999,
    period: 'month',
    color: '#F26818',
    gradient: 'from-blue-500/20 to-cyan-500/10',
    popular: false,
    features: [
      'Full gym access',
      'Basic fitness assessment',
      'Locker room access',
      'Group classes (2/month)',
      'Standard equipment',
    ],
    notIncluded: ['Personal training', 'Nutrition coaching', 'Priority booking'],
  },
  {
    id: 'quarterly',
    name: 'Quarterly',
    price: 2499,
    period: '3 months',
    color: '#C94E05',
    gradient: 'from-purple-500/20 to-pink-500/10',
    popular: true,
    savings: 'Save ₹498',
    features: [
      'Full gym access',
      'Complete fitness assessment',
      'Locker room access',
      'Unlimited group classes',
      'All equipment access',
      '2 Personal training sessions',
      'Nutrition consultation',
    ],
    notIncluded: ['Priority booking'],
  },
  {
    id: 'yearly',
    name: 'Annual',
    price: 7999,
    period: 'year',
    color: '#FF8A3D',
    gradient: 'from-cyan-500/20 to-green-500/10',
    popular: false,
    savings: 'Save ₹3,989',
    features: [
      'Full gym access',
      'Advanced fitness assessment',
      'Premium locker room access',
      'Unlimited group classes',
      'All equipment access',
      '12 Personal training sessions',
      'Monthly nutrition coaching',
      'Priority class booking',
      'Free guest passes (2)',
      'Supplement discount (10%)',
    ],
    notIncluded: [],
  },
];

export const NAV_LINKS = [
  { path: '/', label: 'Home' },
  { path: '/about', label: 'About' },
  { path: '/programs', label: 'Programs' },
  { path: '/trainers', label: 'Trainers' },
  { path: '/membership', label: 'Membership' },
  { path: '/contact', label: 'Contact' },
];
